import type { Metadata, Viewport } from "next";
import { Poppins, Archivo, Mulish } from "next/font/google";
import "./../styles/globals.css";
import ScrollToTop from "@components/common/scroll-to-top";
import { cn } from "lib/utils/utils";
import HeaderServer from "@components/common/header/header.server";
import { ThemeProvider } from "./providers/theme";
import { InitIcons } from "@components/ui/LucideIcon";
import { ToastProvider } from "./providers/toast";
import Footer from "@components/common/footer/page";

const poppinSans = Poppins({
  variable: "--font-poppin-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true, // Critical font
});

const archivoSans = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
  display: "swap",
  preload: false, // Only preload if heavily used
});

const mulishSans = Mulish({
  variable: "--font-mulish-sans",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

// Viewport configuration for better mobile experience
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="vi"
      suppressHydrationWarning
      className={cn(
        poppinSans.variable,
        archivoSans.variable,
        mulishSans.variable
      )}
    >
      <body
        className={cn(
          "bg-background font-poppins antialiased",
          "selection:bg-primary/20 selection:text-primary-foreground",
          "overflow-x-hidden"
        )}
      >
        <ThemeProvider>
          <ToastProvider>
            <InitIcons />
            <HeaderServer />
            <div className="relative flex flex-col min-h-screen">
              {children}
            </div>
            <ScrollToTop />
            <Footer />
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
